// Generated by CoffeeScript 1.6.2
(function() {
  var feedback;

  $(document).on("submit", "#contact-form", function(e) {
    var analytics_info, email, message, name, verify,
      _this = this;

    e.preventDefault();
    email = $(this).find('input[name=email]').val();
    name = $(this).find('input[name=name]').val();
    message = $(this).find('textarea[name=message]').val();
    verify = $(this).find('input[name=verify]').val();
    if (!(email && name && message && verify)) {
      return feedback("Please fill out all the fields.");
    }
    $(this).find('button').disable_button();
    analytics_info = "Previous page: " + document.referrer;
    return $(this).ajaxSubmit({
      data: {
        more: {
          analytics_info: analytics_info
        }
      },
      success: function(data) {
        $(_this).find('button').disable_button();
        feedback("Verification failed.");
        if (data.status === 'success') {
          $(_this).resetForm();
          return feedback("Thanks for contacting us. We'll be in touch shortly.");
        }
      }
    });
  });

  feedback = function(msg) {
    return $('#contact-us-feedback').hide().text(msg).fadeIn(300);
  };

}).call(this);
