// Generated by CoffeeScript 1.6.2
(function() {
  $(document).on('submit', '.download-ebook-form', function(e) {
    var downloadUrl, email,
      _this = this;

    e.preventDefault();
    downloadUrl = $('.gh-link').attr('href');
    email = $(this).find('input').val();
    ga('send', 'event', 'Download ebook');
    return $.getJSON("http://dobt.us7.list-manage1.com/subscribe/post-json?u=9f7643525159ed54ae9670c8a" + ("&amp;id=9b82ed8ef1&c=?&EMAIL=" + email), function() {
      $(_this).hide();
      $(".download-ebook-link").show();
      return window.location = downloadUrl;
    });
  });

}).call(this);
